### ISSUE TITLE
部分接口报错

### ISSUE THREAD

**Issue by weidoufu** [Baiyuetribe/kamiFaka#130]
你好，安装完成之后登陆后台接口报错，具体如下，请问这是什么问题呢？

Traceback (most recent call last):
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Program Files\Python38\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_f
unction
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python38\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 1952, in full_dispatch_reque
st
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Python38\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_f
unction
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 1821, in handle_user_excepti
on
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Python38\Lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 1950, in full_dispatch_reque
st
    rv = self.dispatch_request()
  File "C:\Program Files\Python38\Lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Program Files\Python38\Lib\site-packages\flask_limiter\extension.py", line 732, in __inne
r
    return current_app.ensure_sync(obj)(*a, **k)
  File "C:\Program Files\Python38\Lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'ensure_sync'

**Comment by Baiyuetribe** [comment]
我也不知道，全是依赖包的报错

**Comment by weidoufu** [comment]
window7系统，python3.8.10版本，GET请求方式没报错，POST方式的就会报这个问题
