### ISSUE TITLE
对接v免签微信时，在商品付款出现二维码时，右侧提示请付款undefined元

### ISSUE THREAD

**Issue by kanadeblisst** [Baiyuetribe/kamiFaka#71]
对接v免签微信时，在商品付款出现二维码时，右侧提示请付款undefined元

虽然会出现付款二维码，但是微信扫码显示手机监控端状态掉线。

但是我在v免签测试接口：http://域名/example。是正常监控到消息的。

而且我单独请求：http://域名/getState获取的结果也是正常的。结果如下：
{
  "code": 1,
  "msg": "成功",
  "data": {
    "lastheart": "1620910779",
    "lastpay": "1620910687",
    "jkstate": "1"
  }
}

使用支付宝的当面付付款是正常的。用baiyuetribe/kamifaka:latest镜像搭建的

**Comment by Baiyuetribe** [comment]
掉线就是这样设计的，不是bug

**Comment by kanadeblisst** [comment]
您好，项目中对接v免签的代码应该在vmpay.py吧。我将代码中web_url.key和host_api换成自己的接口和秘钥，然后调用create_order方法是正常返回结果的，接口结果如下：
{"code":1,"msg":"成功","data":{"payId":"22211","orderId":"202105161605182217","payType":1,"price":2.5,"reallyPrice":"2.52","payUrl":"wxp:\/\/f2f0mnvhFa8lNz9HFx8y2VHIeqZgebAhbXlA","isAuto":1,"state":0,"timeOut":"5","date":1621154358}}

create_order方法返回值如下：
{'qr_code': 'wxp://f2f0mnvhFa8lNz9HFx8y2VHIeqZgebAhbXlA', 'payjs_order_id': '202105161605182217', 'reallyPrice': '2.52', 'redirect': 2}

这个二维码链接也是可以正常扫码的。请问使用docker搭建的，docker容器内是否有日志文件，我想看一下哪一步出错了

**Comment by kanadeblisst** [comment]
查看容器日志发现错误信息
```
ImmutableMultiDict([])
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 756, in _write_bytes
    self._sock.sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 666, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 759, in _write_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/base.py", line 89, in __init__
    self._empty_listeners = self._empty_listener_reg[instance_cls]
  File "/usr/local/lib/python3.8/weakref.py", line 383, in __getitem__
    return self.data[ref(key)]
KeyError: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 756, in _write_bytes
    self._sock.sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 666, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 759, in _write_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 756, in _write_bytes
    self._sock.sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 666, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 759, in _write_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
```
我试着重新创建一个不使用mysql环境变量的容器，这次的运行都正常

**Comment by kanadeblisst** [comment]
不使用MySQL运行了几单后还是出现一样的问题，后面v免签服务器都没有创建订单的请求了，重新创建容器也是一样。我刻意去试了下独角数卡对接一下v免签，发现创建订单和支付都是正常的。docker也没有日志输出

**Comment by blissvisitor** [comment]
我也遇到相同的问题，微信扫码支付成功，但是去去校验是否支付成功，会一直报错

ImmutableMultiDict([])
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 756, in _write_bytes
    self._sock.sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 666, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 759, in _write_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/base.py", line 89, in __init__
    self._empty_listeners = self._empty_listener_reg[instance_cls]
  File "/usr/local/lib/python3.8/weakref.py", line 383, in __getitem__
    return self.data[ref(key)]
KeyError: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 756, in _write_bytes
    self._sock.sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 666, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 759, in _write_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 756, in _write_bytes
    self._sock.sendall(data)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall
    return _sendall(self, data_memory, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall
    timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk
    data_sent += socket.send(chunk, flags)
  File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 666, in do_rollback
    dbapi_connection.rollback()
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback
    self._execute_command(COMMAND.COM_QUERY, "ROLLBACK")
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 814, in _execute_command
    self._write_bytes(packet)
  File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 759, in _write_bytes
    raise err.OperationalError(
pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")

**Comment by blissvisitor** [comment]
> 我也遇到相同的问题，微信扫码支付成功，但是去去校验是否支付成功，会一直报错
> 
> ImmutableMultiDict([]) Exception during reset or similar Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 756, in _write_bytes self._sock.sendall(data) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall return _sendall(self, data_memory, flags) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall timeleft = __send_chunk(socket, chunk, flags, timeleft, end) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk data_sent += socket.send(chunk, flags) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send return self._sock.send(data, flags) BrokenPipeError: [Errno 32] Broken pipe
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy fairy._reset(pool) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset pool._dialect.do_rollback(self) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 666, in do_rollback dbapi_connection.rollback() File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback self._execute_command(COMMAND.COM_QUERY, "ROLLBACK") File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 814, in _execute_command self._write_bytes(packet) File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 759, in _write_bytes raise err.OperationalError( pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))") Exception during reset or similar Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/sqlalchemy/event/base.py", line 89, in **init** self._empty_listeners = self._empty_listener_reg[instance_cls] File "/usr/local/lib/python3.8/weakref.py", line 383, in **getitem** return self.data[ref(key)] KeyError:
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 756, in _write_bytes self._sock.sendall(data) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall return _sendall(self, data_memory, flags) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall timeleft = __send_chunk(socket, chunk, flags, timeleft, end) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk data_sent += socket.send(chunk, flags) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send return self._sock.send(data, flags) BrokenPipeError: [Errno 32] Broken pipe
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy fairy._reset(pool) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset pool._dialect.do_rollback(self) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 666, in do_rollback dbapi_connection.rollback() File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback self._execute_command(COMMAND.COM_QUERY, "ROLLBACK") File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 814, in _execute_command self._write_bytes(packet) File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 759, in _write_bytes raise err.OperationalError( pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))") Exception during reset or similar Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 756, in _write_bytes self._sock.sendall(data) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 699, in sendall return _sendall(self, data_memory, flags) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 409, in _sendall timeleft = __send_chunk(socket, chunk, flags, timeleft, end) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 338, in __send_chunk data_sent += socket.send(chunk, flags) File "/usr/local/lib/python3.8/site-packages/gevent/_socketcommon.py", line 722, in send return self._sock.send(data, flags) BrokenPipeError: [Errno 32] Broken pipe
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 676, in _finalize_fairy fairy._reset(pool) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 881, in _reset pool._dialect.do_rollback(self) File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 666, in do_rollback dbapi_connection.rollback() File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 479, in rollback self._execute_command(COMMAND.COM_QUERY, "ROLLBACK") File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 814, in _execute_command self._write_bytes(packet) File "/usr/local/lib/python3.8/site-packages/pymysql/connections.py", line 759, in _write_bytes raise err.OperationalError( pymysql.err.OperationalError: (2006, "MySQL server has gone away (BrokenPipeError(32, 'Broken pipe'))")
已经好了，这个没配对
<img width="1049" alt="image" src="https://github.com/Baiyuetribe/kamiFaka/assets/16833909/cc947ed8-40fc-4982-a661-6dcd9f3eab03">
